# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rails-dev-boost}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Roman Le N\303\251grate", "thedarkone"]
  s.date = %q{2010-11-11}
  s.description = %q{Make your Rails app 10 times faster in development mode}
  s.email = %q{roman.lenegrate@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.markdown",
     "TODO.txt",
     "init.rb",
  ] +
  Dir.glob("lib/**/*.rb") +
  Dir.glob("test/**/*")
  s.homepage = %q{http://github.com/thedarkone/rails-dev-boost}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Speeds up Rails development mode}
  s.test_files = Dir.glob("test/**/*")

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

